In [1]:
import numpy as np
from IPython.display import display, Markdown

In [2]:
def f(X):
    return (X[2] + 2) * X[1] * X[0]**2

def g1(X):
    return 1 - ( X[1]**3 * X[2] )/( 71785 * X[0]**4 )

def g2(X):
    return ( 4 * X[1]**2 - X[0] * X[1] ) / ( 12566 * (X[1] * X[0]**3 - X[0]**4) ) + 1 / (5108 * X[0]**2) - 1

def g3(X):
    return 1 - ( 140.45 * X[0] ) / ( X[1]**2 * X[2] )

def g4(X):
    return ( X[0] + X[1] ) / 1.5 - 1

In [3]:
def GeneratePop(PopSize):
    X1 = np.random.uniform(0.05, 2, [PopSize, 1])
    X2 = np.random.uniform(0.25, 1.30, [PopSize, 1])
    X3 = np.random.uniform(2.00, 15.0, [PopSize, 1])
    X = np.concatenate((X1, X2, X3), axis = 1)
    return X

In [4]:
def Evaluate(X):
    if X[0] < 0.05 or X[0] > 2.00:
        #print("1")
        return False;
    if X[1] < 0.25 or X[1] > 1.30:
        #print("2")
        return False;
    if X[2] < 2.00 or X[2] > 15.0:
        #print("3")
        return False;
    if g1(X) > 0:
        #print("4")
        return False;
    if g2(X) > 0:
        #print("5")
        return False;
    if g3(X) > 0:
        #print("6")
        return False;
    if g4(X) > 0:
        #print("7")
        return False;
    return True;

In [11]:
PopSize = 100000
InitPopulation = GeneratePop(PopSize)

In [12]:
(Xa, fa) = (Xb, fb) = (Xd, fd) = (InitPopulation[0], f(InitPopulation[0]))
print("------------------   Population  ------------------")
Population = []
for X in InitPopulation:
    if Evaluate(X):
        if f(X) < fa:
            (Xd, fd) = (Xb, fb)
            (Xb, fb) = (Xa, fa)
            (Xa, fa) = (X, f(X))
        elif f(X) < fb:
            (Xd, fd) = (Xb, fb)
            (Xb, fb) = (X, f(X))
        elif f(X) < fd:
            (Xd, fd) = (X, f(X))
        print(X, f(X))
        Population.append(X)
print("------------------      TOP3     ------------------")
display(Markdown(f"$X_{{\\alpha}} = $ {Xa} | $ f(X_{{\\alpha}}) = $ {fa}"))
display(Markdown(f"$X_{{\\beta}} = $ {Xb} | $ f(X_{{\\beta}}) = $ {fb}"))
display(Markdown(f"$X_{{\\delta}} = $ {Xd} | $ f(X_{{\\delta}}) = $ {fd}"))
display(Markdown("---"))
print("Valid Population size =", len(Population))

------------------   Population  ------------------
[ 0.06732424  0.66983386 12.84212223] 0.045061545168191296
[0.07886866 1.27110021 3.26981228] 0.041666194334318056
[0.09066817 0.95845694 9.57497312] 0.09120157488402698
[0.07154358 1.01238196 9.51444249] 0.05966624155617132
[ 0.0830377   0.85419175 10.21486404] 0.07194400954114744
[ 0.10377859  1.08594975 11.49690005] 0.15785535229460737
[ 0.12443394  1.20365366 11.25101887] 0.24696109462295668
[0.09526347 1.2495422  5.92610841] 0.08988014392405981
[ 0.07945019  0.63300829 13.68873894] 0.06268842414084022
[ 0.09536734  0.81779693 14.0952093 ] 0.11971302939497926
[ 0.09489137  1.10700324 10.69652679] 0.12655730952625313
[0.09761012 0.93708373 8.85616678] 0.09692695377808483
[ 0.08830399  0.95816283 11.74710673] 0.10270965771548743
[0.08710668 1.21262928 7.85191118] 0.09064659000816044
[ 0.06821361  0.77655565 12.94525904] 0.054003022436731864
[ 0.0822269   0.72237574 12.27429594] 0.06971812525236702
[0.07493211 1.17162098 5.11810037] 

[0.11796308 1.22040785 9.44664288] 0.19439064436670334
[0.11412169 1.22753542 6.9954184 ] 0.14381088435903888
[ 0.0675345   0.75765876 14.50405477] 0.057031623087856385
[0.07515084 0.7218967  8.0849238 ] 0.04111642419654984
[ 0.07992695  0.66137023 11.80464486] 0.05832521224953282
[ 0.06999569  0.71130943 14.76619989] 0.05842998760053776
[0.09478628 1.19843188 3.92467259] 0.06379235759239708
[0.08440245 0.90065318 7.35211552] 0.060003638148246975
[ 0.0758179   0.717375   14.70047975] 0.06886819105589108
[ 0.11567167  1.00308812 13.4873645 ] 0.20785985605189958
[0.08725611 1.04312871 8.87666376] 0.08638241104606949
[0.09539827 1.11863069 5.08197221] 0.07209779423531505
[ 0.08836093  0.79564951 13.58914287] 0.09684219492245501
[ 0.09718057  0.81983912 11.86265325] 0.10733315365858155
[ 0.07718089  0.7373752  12.16953212] 0.06223914987312365
[ 0.07075729  0.69789204 12.89327033] 0.05203800587077772
[ 0.07520847  0.70145956 14.50107384] 0.06547090799973822
[ 0.06861847  0.64800243 13.68620

$X_{\alpha} = $ [ 0.05404894  0.40680499 10.21041193] | $ f(X_{\alpha}) = $ 0.014510784061568329

$X_{\beta} = $ [ 0.05256995  0.34257521 14.99168868] | $ f(X_{\beta}) = $ 0.01608672499207867

$X_{\delta} = $ [ 0.05286282  0.34833873 14.88537898] | $ f(X_{\delta}) = $ 0.01643664389477605

---

Valid Population size = 709


In [7]:
def CalculateNewX(X, a, i):
    r1 = np.random.uniform(0.0, 1.0)
    r2 = np.random.uniform(0.0, 1.0)
    A = 2 * a * r1 - a
    C = 2 * r2
    D = np.abs(C * X - Population[i])
    return X - A * D
    

In [8]:
def Callibrate(Xnew):
    if Xnew[0] < 0.05:
        Xnew[0] = 0.05
    if Xnew[0] > 2.00:
        Xnew[0] = 2.00
    if Xnew[1] < 0.25:
        Xnew[1] = 0.25
    if Xnew[1] > 1.30:
        Xnew[1] = 1.30
    if Xnew[2] < 2.00:
        Xnew[2] = 2.00
    if Xnew[2] > 15.00:
        Xnew[2] = 15.00

In [9]:
maxIter = 5
print("Population Size =", len(Population))
for Iter in range(1, maxIter + 1):
    display(Markdown("# Iteration N°%d"%Iter))
    for i in range(len(Population)):
        a = 2 * (1 - Iter / maxIter)
        X1 = CalculateNewX(Xa, a, i)
        X2 = CalculateNewX(Xb, a, i)
        X3 = CalculateNewX(Xd, a, i)
        Xnew = (X1 + X2 + X3) / 3
        Callibrate(Xnew)
        if f(Xnew) < f(Population[i]) and Evaluate(Xnew):
            print(Population[i], "with index", i, "has been updated with", Xnew)
            Population[i] = Xnew
            
    for X in Population:
        if f(X) < fa:
            (Xd, fd) = (Xb, fb)
            (Xb, fb) = (Xa, fa)
            (Xa, fa) = (X, f(X))
        elif f(X) < fb:
            (Xd, fd) = (Xb, fb)
            (Xb, fb) = (X, f(X))
        elif f(X) < fd:
            (Xd, fd) = (X, f(X))
    
    display(Markdown(f"$X_{{\\alpha}} = $ {Xa} | $ f(X_{{\\alpha}}) = $ {fa}"))
    display(Markdown(f"$X_{{\\beta}} = $ {Xb} | $ f(X_{{\\beta}}) = $ {fb}"))
    display(Markdown(f"$X_{{\\delta}} = $ {Xd} | $ f(X_{{\\delta}}) = $ {fd}"))
    display(Markdown("---"))



Population Size = 744


# Iteration N°1

[ 0.09255613  0.83665844 10.30185158] with index 0 has been updated with [0.06026696 0.50475943 9.18439701]
[ 0.12746373  1.15462913 12.69031453] with index 8 has been updated with [ 0.0819682   0.68843286 11.91995419]
[ 0.09615048  0.99817601 10.74991421] with index 9 has been updated with [ 0.06067642  0.51812854 10.35196758]
[ 0.07713293  0.93431606 11.35256522] with index 13 has been updated with [ 0.06532977  0.62583902 13.9151453 ]
[ 0.0764434   0.57566032 14.42283924] with index 15 has been updated with [ 0.06265147  0.50158089 10.79001343]
[ 0.11081506  1.00836465 12.82977569] with index 24 has been updated with [0.06082159 0.53882979 8.28622328]
[ 0.1049753   0.89631743 12.94871555] with index 26 has been updated with [ 0.05717729  0.4449309  11.15788548]
[0.09684304 1.07682253 8.12979848] with index 32 has been updated with [0.08163481 0.74011142 9.79754856]
[0.06998782 0.70191571 6.01589422] with index 37 has been updated with [ 0.05825111  0.53165537 12.05722939]
[ 0.071938

[ 0.06830317  0.70804352 14.55937253] with index 415 has been updated with [ 0.06379076  0.51712903 11.26675053]
[ 0.08640392  0.98602988 10.17178441] with index 420 has been updated with [ 0.06454804  0.55261894 11.24591534]
[ 0.07434217  0.68453783 14.5468023 ] with index 421 has been updated with [ 0.07257736  0.5736257  13.88648128]
[0.07584256 0.73716535 9.87665411] with index 423 has been updated with [ 0.06472656  0.5841343  11.20092353]
[ 0.11343218  1.08690769 10.60935555] with index 428 has been updated with [ 0.09012887  0.82060407 11.3187632 ]
[ 0.08873756  0.87907522 14.9633081 ] with index 438 has been updated with [ 0.06622033  0.5803503  13.13550037]
[0.08518561 1.01867431 5.59200389] with index 440 has been updated with [ 0.0630152   0.58264505 11.09479362]
[ 0.09292524  0.90305058 14.17312943] with index 448 has been updated with [ 0.08049396  0.69870106 12.39107386]
[ 0.10318743  1.02636635 13.74224328] with index 449 has been updated with [ 0.09004043  0.83209736 15

$X_{\alpha} = $ [ 0.05229892  0.3507     13.17278971] | $ f(X_{\alpha}) = $ 0.014554143972721121

$X_{\beta} = $ [ 0.05229892  0.3507     13.17278971] | $ f(X_{\beta}) = $ 0.014554143972721121

$X_{\delta} = $ [0.05542229 0.43133072 9.40051381] | $ f(X_{\delta}) = $ 0.01510440848423624

---

# Iteration N°2

[0.06026696 0.50475943 9.18439701] with index 0 has been updated with [ 0.05559743  0.40009034 12.19743057]
[ 0.11804502  1.04439775 12.96056251] with index 2 has been updated with [ 0.07306911  0.56995779 13.8941689 ]
[0.08392109 0.81640535 7.90860357] with index 4 has been updated with [ 0.05697407  0.40774904 12.3986684 ]
[ 0.10401956  1.101496   11.23014817] with index 12 has been updated with [ 0.06363245  0.56293629 15.        ]
[ 0.06265147  0.50158089 10.79001343] with index 15 has been updated with [ 0.05376903  0.36508252 12.88424168]
[0.06789988 0.61745743 8.26093923] with index 18 has been updated with [ 0.05469952  0.41021002 10.20676965]
[0.09509763 1.20745545 5.1919178 ] with index 28 has been updated with [ 0.05931315  0.46543053 11.8786817 ]
[ 0.07858003  0.77670709 14.95180135] with index 31 has been updated with [ 0.06617437  0.5672381  11.97962624]
[ 0.0818234   0.64692898 12.70438273] with index 35 has been updated with [ 0.06079811  0.44301087 13.05454205]
[ 0.058

[0.09476172 0.95637954 7.15795361] with index 381 has been updated with [ 0.06610455  0.51013605 11.76997213]
[0.07345341 1.12941628 4.35320964] with index 384 has been updated with [ 0.06176347  0.47648469 11.28725865]
[0.11167225 1.10486514 8.33275684] with index 392 has been updated with [ 0.05474042  0.40505751 12.18334018]
[0.07871387 1.1465618  5.25008738] with index 396 has been updated with [ 0.06246554  0.58974369 12.96974111]
[ 0.063372    0.48691863 12.49327067] with index 398 has been updated with [ 0.05674465  0.40809665 12.31731692]
[0.08317183 0.75636146 8.77714248] with index 403 has been updated with [ 0.07302988  0.57536123 12.85265674]
[ 0.08529061  0.84895765 15.        ] with index 404 has been updated with [ 0.05829254  0.48177774 15.        ]
[0.07940821 0.95282897 4.61364528] with index 405 has been updated with [ 0.05651657  0.44967828 12.78226428]
[0.09933266 1.02636281 7.83067746] with index 408 has been updated with [ 0.07163363  0.55810783 12.84117802]
[ 0.

[0.0624353  0.51038603 9.40239868] with index 735 has been updated with [ 0.06012392  0.4687789  10.80426068]
[ 0.07395685  0.5629726  12.70116489] with index 736 has been updated with [ 0.05659803  0.39875242 12.55190068]
[ 0.07759217  0.75007281 10.78056715] with index 743 has been updated with [ 0.05847596  0.49768835 13.70854243]


$X_{\alpha} = $ [ 0.05217958  0.36537057 11.77244176] | $ f(X_{\alpha}) = $ 0.01370079109986181

$X_{\beta} = $ [ 0.05407838  0.38660168 10.78221186] | $ f(X_{\beta}) = $ 0.014451638559747439

$X_{\delta} = $ [ 0.05319597  0.38404007 11.30120883] | $ f(X_{\delta}) = $ 0.014455235940092263

---

# Iteration N°3

[0.06878394 0.83986501 9.10840844] with index 1 has been updated with [ 0.05866795  0.47614146 11.49401455]
[ 0.05874074  0.48281069 12.92684704] with index 19 has been updated with [ 0.05762771  0.41149554 12.26463568]
[ 0.07664929  0.66654038 12.11533642] with index 22 has been updated with [ 0.06016944  0.44223178 12.26902712]
[ 0.0983754   1.00002064 13.61405382] with index 23 has been updated with [ 0.05458349  0.38079017 12.04242549]
[0.08779065 0.84763296 9.01997351] with index 25 has been updated with [ 0.05727456  0.41735215 10.86427216]
[ 0.05931315  0.46543053 11.8786817 ] with index 28 has been updated with [ 0.05437487  0.38628025 11.59906499]
[0.1075508  1.15643206 7.39020863] with index 40 has been updated with [ 0.05848693  0.46050611 10.64219721]
[0.08401823 0.90001637 9.61098086] with index 43 has been updated with [ 0.06020032  0.47737704 11.65782092]
[ 0.08342248  0.62550662 15.        ] with index 46 has been updated with [ 0.06911351  0.50094914 13.90218837]
[0.06

[ 0.08465902  0.73868504 12.91598085] with index 332 has been updated with [ 0.0753096   0.59729032 13.62331978]
[ 0.06039906  0.42323373 14.34408227] with index 334 has been updated with [ 0.06023825  0.42995105 12.785405  ]
[0.06116279 0.60203199 8.92059476] with index 337 has been updated with [ 0.05724182  0.4389002  12.97395557]
[0.0840134  0.86811385 5.58173319] with index 339 has been updated with [ 0.05524969  0.40065678 13.26288667]
[ 0.0644048   0.49528049 12.37217942] with index 343 has been updated with [ 0.0563239   0.40335556 11.96978212]
[ 0.06897627  0.66494467 10.09036521] with index 348 has been updated with [ 0.06438152  0.47087266 12.62606875]
[0.10726377 1.20856884 8.80355098] with index 353 has been updated with [ 0.07081788  0.58147246 11.34772479]
[ 0.07377715  0.73379782 14.68980904] with index 356 has been updated with [ 0.05488631  0.43346052 11.67195754]
[ 0.05822869  0.40670223 13.41504628] with index 358 has been updated with [ 0.05856442  0.41668328 12.56

[0.07348903 1.00665568 6.56445465] with index 643 has been updated with [ 0.06129537  0.50769885 13.41454437]
[ 0.07905659  0.79700553 12.15034869] with index 648 has been updated with [ 0.07494338  0.6669852  15.        ]
[ 0.06819678  0.55289721 15.        ] with index 653 has been updated with [ 0.05527764  0.41268351 11.75405193]
[ 0.06169809  0.46448627 12.66620908] with index 659 has been updated with [ 0.05566886  0.39189119 11.66178034]
[ 0.06048791  0.47417843 11.28705234] with index 660 has been updated with [ 0.05784027  0.43265996 11.7762956 ]
[0.0721515 1.0572846 8.7092671] with index 662 has been updated with [ 0.06296039  0.55669987 12.8260972 ]
[ 0.11283276  1.07649065 13.52719281] with index 663 has been updated with [ 0.0775137   0.66604081 14.02534295]
[ 0.05744739  0.39695146 15.        ] with index 664 has been updated with [ 0.05382886  0.38898782 10.42544833]
[0.09031143 1.03811272 5.55963297] with index 667 has been updated with [ 0.07204318  0.60282917 10.56238

$X_{\alpha} = $ [ 0.05211866  0.36076267 11.35410641] | $ f(X_{\alpha}) = $ 0.013086480651621676

$X_{\beta} = $ [ 0.05228866  0.36442647 11.17555292] | $ f(X_{\beta}) = $ 0.013127855324487328

$X_{\delta} = $ [ 0.05237521  0.37202628 11.12831992] | $ f(X_{\delta}) = $ 0.013397827834750594

---

# Iteration N°4

[0.09330666 1.20397926 7.01593508] with index 3 has been updated with [ 0.05943193  0.52185059 12.16597187]
[ 0.08746231  0.71540038 11.58836076] with index 5 has been updated with [ 0.05925773  0.42512029 11.99804385]
[0.10034637 1.24281273 7.84295658] with index 17 has been updated with [ 0.06926967  0.60885916 12.14674555]
[ 0.08101564  0.60689724 14.47147722] with index 21 has been updated with [ 0.05617718  0.39861232 12.00102797]
[ 0.06016944  0.44223178 12.26902712] with index 22 has been updated with [ 0.0546605   0.38329056 11.67259405]
[ 0.05458349  0.38079017 12.04242549] with index 23 has been updated with [ 0.0524378   0.36793941 11.21967621]
[ 0.11005398  0.98039133 14.50385036] with index 30 has been updated with [ 0.0615881   0.45118333 12.19778289]
[ 0.09140023  0.92336717 11.03816893] with index 33 has been updated with [ 0.05985487  0.44483275 11.49523877]
[ 0.05848693  0.46050611 10.64219721] with index 40 has been updated with [ 0.05494005  0.39659008 11.36823212]


[0.09142277 0.99793363 5.24829437] with index 292 has been updated with [ 0.06053921  0.48811454 12.18033092]
[0.07501475 0.85190537 8.48710076] with index 294 has been updated with [ 0.05512842  0.39912306 11.77913767]
[0.07173021 0.94218718 9.36704548] with index 299 has been updated with [ 0.05564935  0.40306186 11.92544935]
[ 0.07258146  0.67000066 13.93359676] with index 300 has been updated with [ 0.05805621  0.42646951 12.28142303]
[ 0.0641959   0.50813886 11.63503048] with index 302 has been updated with [ 0.05276335  0.37751064 11.39426241]
[ 0.08034177  0.69543975 11.6525661 ] with index 307 has been updated with [ 0.06096279  0.44541712 12.34282015]
[ 0.07011188  0.64566856 14.92712741] with index 312 has been updated with [ 0.05273923  0.36861793 11.32690387]
[0.07937963 1.29846515 4.09861714] with index 314 has been updated with [ 0.0541503   0.41553139 11.88788831]
[ 0.05541087  0.40214444 12.30008269] with index 316 has been updated with [ 0.05491806  0.38528896 11.80246

[ 0.06963582  0.58983923 12.91542611] with index 564 has been updated with [ 0.05203502  0.36194706 11.38761968]
[0.06842183 0.73648584 4.55589253] with index 565 has been updated with [ 0.05461735  0.41264067 13.05155881]
[ 0.06742681  0.58478181 13.21201645] with index 566 has been updated with [ 0.05807403  0.41536039 12.36305676]
[0.07365739 0.98984019 2.36851257] with index 567 has been updated with [ 0.05607174  0.4196531  11.17733212]
[ 0.05211866  0.36076267 11.35410641] with index 569 has been updated with [ 0.0520226   0.36401451 11.17423985]
[ 0.05791127  0.43091067 12.30939601] with index 570 has been updated with [ 0.05658982  0.39938788 12.12788569]
[0.06504847 0.75333215 7.34627222] with index 573 has been updated with [ 0.05772301  0.46041038 11.93866128]
[ 0.06184397  0.53912705 13.27306109] with index 581 has been updated with [ 0.05916553  0.43495964 12.71413304]
[ 0.06386153  0.46583998 13.11856979] with index 584 has been updated with [ 0.05292737  0.37062445 11.35

$X_{\alpha} = $ [ 0.05192671  0.36082781 11.16746726] | $ f(X_{\alpha}) = $ 0.012811025911661524

$X_{\beta} = $ [ 0.05205525  0.36377508 11.1645397 ] | $ f(X_{\beta}) = $ 0.012976804140919571

$X_{\delta} = $ [ 0.0520226   0.36401451 11.17423985] | $ f(X_{\delta}) = $ 0.01297861577203341

---

# Iteration N°5

[ 0.05559743  0.40009034 12.19743057] with index 0 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05866795  0.47614146 11.49401455] with index 1 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.07306911  0.56995779 13.8941689 ] with index 2 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05943193  0.52185059 12.16597187] with index 3 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05697407  0.40774904 12.3986684 ] with index 4 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05925773  0.42512029 11.99804385] with index 5 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.06821672  0.50593303 14.85011445] with index 6 has been updated with [ 0.05200152  0.36287246 11.16874894]
[0.103222   1.07885869 6.49077672] with index 7 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.0819682   0.68843286 11.91995419] with index 8 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.

[0.07298367 1.0276098  2.2877967 ] with index 104 has been updated with [ 0.05200152  0.36287246 11.16874894]
[0.06492361 0.58762551 9.4083036 ] with index 105 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05493154  0.38460126 11.78625618] with index 106 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05819614  0.41656849 12.44148877] with index 107 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.07204421  0.6146062  10.3420329 ] with index 108 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.07812793  0.69741541 14.14604568] with index 109 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.06175769  0.53486825 12.10402805] with index 110 has been updated with [ 0.05200152  0.36287246 11.16874894]
[0.0816238  1.22240072 7.01956422] with index 111 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.0524045   0.36321246 11.36315641] with index 112 has been updated with [ 0.05200152  0.36287246 11.16

[ 0.06713295  0.72747672 15.        ] with index 200 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05792499  0.40908211 12.75672254] with index 201 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.06117538  0.51699212 13.12829468] with index 202 has been updated with [ 0.05200152  0.36287246 11.16874894]
[0.07680488 1.00218267 7.09109709] with index 203 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.06407475  0.54036084 13.59204051] with index 204 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.06239464  0.46818156 12.89348693] with index 205 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05540888  0.40181603 12.10984973] with index 206 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.06083786  0.49788591 12.910806  ] with index 207 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.06983522  0.63452553 13.97998174] with index 208 has been updated with [ 0.05200152  0.36287246

[ 0.05480594  0.38368925 11.76201585] with index 343 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.10543242  1.03590521 10.13999023] with index 344 has been updated with [ 0.05200152  0.36287246 11.16874894]
[0.08653792 1.23291777 7.41861095] with index 345 has been updated with [ 0.05200152  0.36287246 11.16874894]
[0.06160834 0.5360485  9.08453171] with index 346 has been updated with [ 0.05200152  0.36287246 11.16874894]
[0.09435832 1.00284831 5.95171819] with index 347 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.06438152  0.47087266 12.62606875] with index 348 has been updated with [ 0.05200152  0.36287246 11.16874894]
[0.08799026 1.26799152 4.25455184] with index 349 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05372329  0.39600344 12.18182271] with index 350 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.06565265  0.67331871 13.97709392] with index 351 has been updated with [ 0.05200152  0.36287246 11.16874

[ 0.05589415  0.40937257 12.08790728] with index 460 has been updated with [ 0.05200152  0.36287246 11.16874894]
[0.09524989 1.22510963 6.71521121] with index 461 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.06795826  0.60461466 11.96814445] with index 462 has been updated with [ 0.05200152  0.36287246 11.16874894]
[0.10834677 1.05236223 8.89735293] with index 463 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05336528  0.37697431 11.49323176] with index 464 has been updated with [ 0.05200152  0.36287246 11.16874894]
[0.08329305 1.05481431 7.62312361] with index 465 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.08044888  0.84640768 11.22212797] with index 466 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05415544  0.38179199 11.74927366] with index 467 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05749502  0.45286083 12.12174157] with index 468 has been updated with [ 0.05200152  0.36287246 11.16

[ 0.06352859  0.52312217 10.46903352] with index 536 has been updated with [ 0.05200152  0.36287246 11.16874894]
[0.08605161 1.08247437 4.85609   ] with index 537 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05714848  0.39904643 12.22326302] with index 538 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05935089  0.43551931 11.79702705] with index 539 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.07716057  0.65241952 15.        ] with index 540 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.06193816  0.56059789 11.43671862] with index 541 has been updated with [ 0.05200152  0.36287246 11.16874894]
[0.07481252 0.96857493 5.77585216] with index 542 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05780314  0.48267082 11.65152685] with index 543 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05352574  0.38311577 11.24170662] with index 544 has been updated with [ 0.05200152  0.36287246 11

[ 0.0549351   0.38006381 11.96781315] with index 628 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05826781  0.44782347 13.14297194] with index 629 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05868433  0.45085902 11.83986557] with index 630 has been updated with [ 0.05200152  0.36287246 11.16874894]
[0.08215878 1.00544351 9.84096205] with index 631 has been updated with [ 0.05200152  0.36287246 11.16874894]
[0.08912012 0.89254922 8.73866032] with index 632 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.06632781  0.5650742  12.82263926] with index 633 has been updated with [ 0.05200152  0.36287246 11.16874894]
[0.08180938 0.8116462  9.63425822] with index 634 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.06309589  0.46150614 13.43344402] with index 635 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.07255742  0.63649155 15.        ] with index 636 has been updated with [ 0.05200152  0.36287246 11.16

[ 0.05391596  0.38220941 11.49635252] with index 721 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.0557301   0.44943157 14.73118978] with index 722 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05488582  0.38837538 11.64636636] with index 723 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05560174  0.38697428 12.01498911] with index 724 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.06119914  0.5074214  13.12535949] with index 725 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05514647  0.42038109 12.15525361] with index 726 has been updated with [ 0.05200152  0.36287246 11.16874894]
[0.08631988 0.90764836 7.44736119] with index 727 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.05432338  0.39324163 11.48342033] with index 728 has been updated with [ 0.05200152  0.36287246 11.16874894]
[ 0.06402725  0.50320849 13.16562386] with index 729 has been updated with [ 0.05200152  0.36287246

$X_{\alpha} = $ [ 0.05192671  0.36082781 11.16746726] | $ f(X_{\alpha}) = $ 0.012811025911661524

$X_{\beta} = $ [ 0.05192671  0.36082781 11.16746726] | $ f(X_{\beta}) = $ 0.012811025911661524

$X_{\delta} = $ [ 0.05200152  0.36287246 11.16874894] | $ f(X_{\delta}) = $ 0.01292202706694707

---